(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter phi: Prop.

Parameter psi: Prop.

Parameter chi: Prop.

Parameter e: Prop.

Parameter y: Prop.

Parameter r: Prop.

(* Why3 goal *)
Theorem Thm06 : ((e -> y \/ r) /\ (y -> r)) -> ~ r -> ~ e.
Proof.
intros (h1,h2) h3.
unfold not.
intro h4.
absurd r.
exact h3.
cut (y\/r).
intro h.
elim h.
exact h2.
intuition.
cut e.
exact h1.
exact h4.
Qed.

