(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter phi: Prop.

Parameter psi: Prop.

Parameter chi: Prop.

(* Why3 goal *)
Theorem Thm04 : True.
Proof.


Qed.

