(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

Parameter phi: Prop.

Parameter psi: Prop.

Parameter chi: Prop.

(* Why3 goal *)
Theorem Thm03 : (phi -> psi) -> ~ psi -> ~ phi.
Proof.
intros h1 h2.
unfold not.
intro h3.
absurd psi.
exact h2.
cut phi.
exact h1.
exact h3.

Qed.

